### ISSUE TITLE
Function is not called 

### ISSUE THREAD

**Issue by noook** [ohheyjosh/isthisaleapyear#1]
https://github.com/ohheyjosh/isthisaleapyear/blob/18053789f3e9fa91f8edbc4665f09976365d022c/index.html#L41

Function after the check is not called, also we could use triple equal assertion.

```js
if (isLeapYear && isLeapYear() === true) {
} /* ... */
```

**Comment by ohheyjosh** [comment]
@noook thanks for catching that and reporting it!
